### ISSUE TITLE
1.2.0 does not seem to run with gist-plugin-2.12_4.8.0

### ISSUE THREAD

**Issue by umq** [nus/gitbucket-plantuml-plugin#15]
got an exception:
```
java.lang.NullPointerException
	at net.sourceforge.plantuml.SourceStringReader.generateImage(SourceStringReader.java:117)
	at com.yotaichino.gitbucket.plugins.plantuml.PlantUMLUtils$.generateImage(PlantUMLUtils.scala:16)
	at com.yotaichino.gitbucket.plugins.plantuml.PlantUMLUtils$.generateSVGImage(PlantUMLUtils.scala:10)
	at com.yotaichino.gitbucket.plugins.plantuml.PlantUMLRenderer.imgEmbedded(PlantUMLRenderer.scala:17)
	at com.yotaichino.gitbucket.plugins.plantuml.PlantUMLRenderer.render(PlantUMLRenderer.scala:13)
	at gitbucket.core.view.helpers$.renderMarkup(helpers.scala:134)
	at gitbucket.gist.html.list$.$anonfun$apply$3(list.template.scala:81)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at gitbucket.gist.html.list$.apply(list.template.scala:47)
	at gitbucket.gist.controller.GistControllerBase._gist(GistController.scala:452)
	at gitbucket.gist.controller.GistControllerBase.$anonfun$$init$$37(GistController.scala:285)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:279)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:189)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:175)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:278)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:277)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:33)
	at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:88)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:189)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:175)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:33)
	at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:82)
	at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:81)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:253)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:251)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:250)
	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:248)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:187)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:153)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:122)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(flashMap.scala:170)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.handle(flashMap.scala:145)
	at org.scalatra.FlashMapSupport.handle$(flashMap.scala:144)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:74)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:178)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:187)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:153)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:122)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(flashMap.scala:170)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.handle(flashMap.scala:145)
	at org.scalatra.FlashMapSupport.handle$(flashMap.scala:144)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:74)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:178)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:187)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:153)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:122)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(flashMap.scala:170)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.handle(flashMap.scala:145)
	at org.scalatra.FlashMapSupport.handle$(flashMap.scala:144)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:74)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:178)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:187)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:153)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:122)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(flashMap.scala:170)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.handle(flashMap.scala:145)
	at org.scalatra.FlashMapSupport.handle$(flashMap.scala:144)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:74)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:178)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:187)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:153)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:33)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:122)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:33)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(flashMap.scala:170)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:33)
	at org.scalatra.FlashMapSupport.handle(flashMap.scala:145)
	at org.scalatra.FlashMapSupport.handle$(flashMap.scala:144)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:33)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at gitbucket.core.servlet.GHCompatRepositoryAccessFilter.doFilter(GHCompatRepositoryAccessFilter.scala:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:190)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:190)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:183)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:190)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1524)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nus** [comment]
@umq 
Thank you for your reporting.

Could you try on commit  b835f6ab9a5d809030498a548ff86511e76601b3 ?

**Comment by umq** [comment]
@nus 
b835f6ab9a5d809030498a548ff86511e76601b3 seems to work for me.
