### ISSUE TITLE
got ERROR with GitBucket 4.30

### ISSUE THREAD

**Issue by umq** [nus/gitbucket-plantuml-plugin#20]
I got ERROR with GitBucket 4.30

```
01:15:16.383 [qtp401625763-38] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-plantuml-plugin-assembly-1.4.0.jar
01:15:16.402 [qtp401625763-38] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-plantuml-plugin-assembly-1.4.0.jar
java.lang.NoSuchMethodError: gitbucket.core.plugin.PluginRegistry.addController(Lgitbucket/core/controller/ControllerBase;Ljava/lang/String;)V
        at Plugin.initialize(Plugin.scala:30)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:357)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:319)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:319)
        at gitbucket.core.plugin.PluginRegistry$.install(PluginRegistry.scala:261)
~
```

This commit might be relevant
https://github.com/gitbucket/gitbucket/commit/694b77294cea10fc4030f177e24c781a73d23baa

**Comment by nus** [comment]
Thanks.

**Comment by nus** [comment]
I fixed this issue.
Could you try [v1.5.0](https://github.com/nus/gitbucket-plantuml-plugin/releases/tag/v1.5.0) ?

**Comment by umq** [comment]
1.5.0 looks good to me

**Comment by nus** [comment]
Thanks😄
